---

mysql_debian_pkgs_default:
  - python3-mysqldb
mysql_release_specific_debian_pkgs:
  xenial:
    - python-mysqldb
  bionic:
    - python-mysqldb
  focal:
    - python3-mysqldb
mysql_debian_pkgs: "{{ mysql_debian_pkgs_default + mysql_release_specific_debian_pkgs[ansible_distribution_release] }}"

mysql_server_pkg: "{{ 'mysql-server-5.7' if mysql_server_version_5_7 is defined and (mysql_server_version_5_7 | bool) else 'mysql-server-5.6' }}"
mysql_server_5_7_pkg: "mysql-server=5.7.*"
mysql_client_5_7_pkg: "mysql-client=5.7.*"
mysql_community_server_5_7_pkg: "mysql-server=5.7.*"

mysql_dir: /etc/mysql

mysql_socket: /var/run/mysqld/mysqld.sock

DEFAULT_MYSQL_CHARACTER_SET: utf8
DEFAULT_MYSQL_COLLATION: utf8_general_ci

MYSQL_DATADIR: "{{ COMMON_BASE_DIR }}/var/mysql"
MYSQL_BIND_ADDRESS: "127.0.0.1"

# can be set to greater value for dedicated database instances
# for example 2G or 4G
MYSQL_INNODB_BUFFER_POOL_SIZE: 256M
