---
MFE_NAME: ' NOT-SET '
MFE_REPO: 'frontend-app-{{ MFE_NAME }}'
MFE_HOME: '{{ COMMON_APP_DIR }}/{{ MFE_NAME }}'
MFE_USER: '{{ MFE_NAME }}'

MFE_GIT_PROTOCOL: '{{ COMMON_GIT_PROTOCOL }}'
MFE_GIT_DOMAIN: '{{ COMMON_GIT_MIRROR }}'
MFE_GIT_PATH: '{{ COMMON_GIT_PATH }}'
MFE_VERSION: 'master'
MFE_GIT_IDENTITY: null

MFE_CODE_DIR: '{{ MFE_HOME }}/{{ MFE_REPO }}'
MFE_NODEENV_DIR: '{{ MFE_HOME }}/nodeenvs/{{ MFE_NAME }}'
MFE_NODEENV_BIN: '{{ MFE_NODEENV_DIR }}/bin'
MFE_NODE_MODULES_DIR: '{{ MFE_CODE_DIR }}/node_modules'
MFE_NODE_BIN: '{{ MFE_NODE_MODULES_DIR }}/.bin'
MFE_NODE_VERSION: '16.13.2'
MFE_NPM_VERSION: '8.1.2'

MFE_DEBIAN_PKGS_DEFAULT:
  - gettext
  - nodeenv
MFE_DEBIAN_PKGS_EXTRA: []
MFE_DEBIAN_PKGS: '{{ MFE_DEBIAN_PKGS_DEFAULT + MFE_DEBIAN_PKGS_EXTRA }}'

MFE_CORS_ALLOWLIST: []
MFE_ALLOW_CORS_HEADERS: false
MFE_MAX_WEBSERVER_UPLOAD: !!null
MFE_ALLOW_CORS_CREDENTIALS: false

MFE_STUDIO_BASE_URL: ''

MFE_HOSTNAME: '~^((stage|prod)-)?{{ MFE_NAME }}.*'
MFE_NGINX_PORT: '80'
MFE_NGINX_READ_TIMEOUT: !!null

MFE_SSL_NGINX_PORT: '443'
MFE_ENABLE_BASIC_AUTH: false

MFE_REPOS:
  - PROTOCOL: '{{ MFE_GIT_PROTOCOL }}'
    DOMAIN: '{{ MFE_GIT_DOMAIN }}'
    PATH: '{{ MFE_GIT_PATH }}'
    REPO: '{{ MFE_REPO }}.git'
    VERSION: '{{ MFE_VERSION }}'
    DESTINATION: '{{ MFE_CODE_DIR }}'
    SSH_KEY: '{{ MFE_GIT_IDENTITY }}'

MFE_NODE_ENV: production
MFE_BASE: "{{ MFE_NAME }}.{{ COMMON_LMS_BASE_URL }}"
MFE_PUBLIC_PATH: "/"
MFE_BASE_SCHEMA: "http"
MFE_BASE_URL: "{{ MFE_BASE_SCHEMA }}://{{ MFE_BASE }}"
MFE_LMS_BASE_URL: "{{ COMMON_LMS_BASE_URL }}"
MFE_ECOMMERCE_BASE_URL: "{{ COMMON_ECOMMERCE_BASE_URL }}"
MFE_LEARNING_BASE_URL: "{{ EDXAPP_LEARNING_MICROFRONTEND_URL }}"
MFE_LOGIN_URL: "{{ MFE_LMS_BASE_URL }}/login"
MFE_LOGOUT_URL: "{{ MFE_LMS_BASE_URL }}/logout"
MFE_SITE_NAME: ""
MFE_MARKETING_SITE_BASE_URL: "{{ MFE_LMS_BASE_URL }}"
MFE_CONTACT_URL: "{{ MFE_MARKETING_SITE_BASE_URL }}/contact"
MFE_CSRF_TOKEN_API_PATH: "/csrf/api/v1/token"
MFE_CREDENTIALS_BASE_URL: ""
MFE_REFRESH_ACCESS_TOKEN_ENDPOINT: "{{ MFE_LMS_BASE_URL }}/login_refresh"
MFE_DATA_API_BASE_URL: "{{ MFE_LMS_BASE_URL }}"
MFE_ACCESS_TOKEN_COOKIE_NAME: "{{ COMMON_JWT_AUTH_COOKIE_HEADER_PAYLOAD }}"
MFE_SUPPORT_URL: "{{ MFE_MARKETING_SITE_BASE_URL }}/contact"
MFE_OPEN_SOURCE_URL: "{{ MFE_MARKETING_SITE_BASE_URL }}/opensource"
MFE_TERMS_OF_SERVICE_URL: "{{ MFE_MARKETING_SITE_BASE_URL }}/tos"
MFE_PRIVACY_POLICY_URL: "{{ MFE_MARKETING_SITE_BASE_URL }}/privacy"
MFE_SEARCH_CATALOG_URL: "{{ MFE_MARKETING_SITE_BASE_URL }}/courses"
MFE_LANGUAGE_PREFERENCE_COOKIE_NAME: "openedx-language-preference"

MFE_LOGO_URL: "{{ COMMON_LOGO_URL }}"
MFE_LOGO_TRADEMARK_URL: "{{ COMMON_LOGO_TRADEMARK_URL }}"
MFE_LOGO_WHITE_URL: "{{ COMMON_LOGO_WHITE_URL }}"
MFE_FAVICON_URL: "{{ COMMON_FAVICON_URL }}"

MFE_FACEBOOK_URL: ""
MFE_TWITTER_URL: ""
MFE_YOU_TUBE_URL: ""
MFE_LINKED_IN_URL: ""
MFE_REDDIT_URL: ""

MFE_APPLE_APP_STORE_URL: ""
MFE_GOOGLE_PLAY_URL: ""

MFE_ENABLE_RG_GAMIFICATION: false

MFE_ENTERPRISE_MARKETING_URL: "{{ MFE_MARKETING_SITE_BASE_URL }}"
MFE_ENTERPRISE_MARKETING_UTM_SOURCE: ""
MFE_ENTERPRISE_MARKETING_UTM_CAMPAIGN: ""
MFE_ENTERPRISE_MARKETING_FOOTER_UTM_MEDIUM: ""

MFE_ORDER_HISTORY_URL: https://order-history.example.com
MFE_USER_INFO_COOKIE_NAME: edx-user-info

MFE_NEW_RELIC_APP_ID: 'fake_app'
MFE_NEW_RELIC_LICENSE_KEY: 'fake_license'

#Learning
MFE_SUPPORT_URL_CALCULATOR_MATH: "https://support.edx.org/hc/en-us/articles/360000038428-Entering-math-expressions-in-assignments-or-the-calculator"
MFE_SUPPORT_URL_ID_VERIFICATION: "https://support.edx.org/hc/en-us/articles/206503858-How-do-I-verify-my-identity"
MFE_SUPPORT_URL_VERIFIED_CERTIFICATE: "https://support.edx.org/hc/en-us/articles/206502008-What-is-a-verified-certificate"

# Discussions MFE
MFE_TA_FEEDBACK_FORM: ''
MFE_STAFF_FEEDBACK_FORM: ''
MFE_DISPLAY_FEEDBACK_BANNER: false

#Course Authoring
MFE_ENABLE_PROGRESS_GRAPH_SETTINGS: false
MFE_ENABLE_TEAM_TYPE_SETTING: false
MFE_ENABLE_NEW_EDITOR_PAGES: true
MFE_BBB_LEARN_MORE_URL: ''

# Authentication (Authn)
MFE_AUTHN_MINIMAL_HEADER: ''
MFE_LOGIN_ISSUE_SUPPORT_LINK: '/login-issue-support-url'
MFE_TOS_AND_HONOR_CODE: "{{ MFE_MARKETING_SITE_BASE_URL }}/honor"
MFE_TOS_LINK: "{{ MFE_TERMS_OF_SERVICE_URL }}"
MFE_PRIVACY_POLICY: "{{ MFE_PRIVACY_POLICY_URL }}"
MFE_USER_SURVEY_COOKIE_NAME: 'openedx-user-survey-type'
MFE_COOKIE_DOMAIN: "{{ EDXAPP_SESSION_COOKIE_DOMAIN }}"
MFE_WELCOME_PAGE_SUPPORT_LINK: "{{ EDXAPP_AUTHN_MICROFRONTEND_URL }}/welcome"
MFE_INFO_EMAIL: 'info@edx.org'
MFE_DISABLE_ENTERPRISE_LOGIN: ''
MFE_REGISTER_CONVERSION_COOKIE_NAME: 'openedx-user-register-conversion'
MFE_ENABLE_COPPA_COMPLIANCE: ''
MFE_MARKETING_EMAILS_OPT_IN: ''
MFE_ZENDESK_KEY: ''
MFE_ZENDESK_LOGO_URL: ''
MFE_APP_ID: ''
MFE_MFE_CONFIG_API_URL: ''
MFE_SHOW_CONFIGURABLE_EDX_FIELDS: true


MFE_ENVIRONMENT_DEFAULT:
  PATH: '{{ MFE_NODEENV_BIN }}:{{ ansible_env.PATH }}'
  NODE_ENV: "{{ MFE_NODE_ENV }}"
  BASE_URL: "{{ MFE_BASE_URL }}"
  PUBLIC_PATH: "{{ MFE_PUBLIC_PATH }}"
  LMS_BASE_URL: "{{ MFE_LMS_BASE_URL }}"
  LOGIN_URL: "{{ MFE_LOGIN_URL }}"
  LOGOUT_URL: "{{ MFE_LOGOUT_URL }}"
  SITE_NAME: "{{ MFE_SITE_NAME }}"
  MARKETING_SITE_BASE_URL: "{{ MFE_MARKETING_SITE_BASE_URL }}"
  CONTACT_URL: "{{ MFE_CONTACT_URL }}"
  CSRF_TOKEN_API_PATH: "{{ MFE_CSRF_TOKEN_API_PATH }}"
  CREDENTIALS_BASE_URL: "{{ MFE_CREDENTIALS_BASE_URL }}"
  REFRESH_ACCESS_TOKEN_ENDPOINT: "{{ MFE_REFRESH_ACCESS_TOKEN_ENDPOINT }}"
  DATA_API_BASE_URL: "{{ MFE_DATA_API_BASE_URL }}"
  ACCESS_TOKEN_COOKIE_NAME: "{{ MFE_ACCESS_TOKEN_COOKIE_NAME }}"
  SUPPORT_URL: "{{ MFE_SUPPORT_URL }}"
  OPEN_SOURCE_URL: "{{ MFE_OPEN_SOURCE_URL }}"
  TERMS_OF_SERVICE_URL: "{{ MFE_TERMS_OF_SERVICE_URL }}"
  PRIVACY_POLICY_URL: "{{ MFE_PRIVACY_POLICY_URL }}"
  SEARCH_CATALOG_URL: "{{ MFE_SEARCH_CATALOG_URL }}"
  FACEBOOK_URL: "{{ MFE_FACEBOOK_URL }}"
  TWITTER_URL: "{{ MFE_TWITTER_URL }}"
  YOU_TUBE_URL: "{{ MFE_YOU_TUBE_URL }}"
  LINKED_IN_URL: "{{ MFE_LINKED_IN_URL }}"
  REDDIT_URL: "{{ MFE_REDDIT_URL }}"
  APPLE_APP_STORE_URL: "{{ MFE_APPLE_APP_STORE_URL }}"
  GOOGLE_PLAY_URL: "{{ MFE_GOOGLE_PLAY_URL }}"
  ENTERPRISE_MARKETING_URL: "{{ MFE_ENTERPRISE_MARKETING_URL }}"
  ENTERPRISE_MARKETING_UTM_SOURCE: "{{ MFE_ENTERPRISE_MARKETING_UTM_SOURCE }}"
  ENTERPRISE_MARKETING_UTM_CAMPAIGN: "{{ MFE_ENTERPRISE_MARKETING_UTM_CAMPAIGN }}"
  ENTERPRISE_MARKETING_FOOTER_UTM_MEDIUM: "{{ MFE_ENTERPRISE_MARKETING_FOOTER_UTM_MEDIUM }}"
  ECOMMERCE_BASE_URL: "{{ MFE_ECOMMERCE_BASE_URL }}"
  ORDER_HISTORY_URL: "{{ MFE_ORDER_HISTORY_URL }}"
  USER_INFO_COOKIE_NAME: "{{ MFE_USER_INFO_COOKIE_NAME }}"
  NEW_RELIC_LICENSE_KEY: '{{ MFE_NEW_RELIC_LICENSE_KEY }}'
  NEW_RELIC_APP_ID: '{{ MFE_NEW_RELIC_APP_ID }}'
  LOGO_URL: "{{ MFE_LOGO_URL }}"
  LOGO_TRADEMARK_URL: "{{ MFE_LOGO_TRADEMARK_URL }}"
  LOGO_WHITE_URL: "{{ MFE_LOGO_WHITE_URL }}"
  FAVICON_URL: "{{ MFE_FAVICON_URL }}"
  LANGUAGE_PREFERENCE_COOKIE_NAME: "{{ MFE_LANGUAGE_PREFERENCE_COOKIE_NAME }}"
  LEGACY_THEME_NAME: "{{ MFE_LEGACY_THEME_NAME }}"
  STUDIO_BASE_URL: "{{ MFE_STUDIO_BASE_URL }}"
  ENABLE_RG_GAMIFICATION: "{{ MFE_ENABLE_RG_GAMIFICATION }}"
  LEARNING_BASE_URL: "{{ MFE_LEARNING_BASE_URL }}"
  TA_FEEDBACK_FORM: "{{ MFE_TA_FEEDBACK_FORM }}"
  STAFF_FEEDBACK_FORM: "{{ MFE_STAFF_FEEDBACK_FORM }}"
  DISPLAY_FEEDBACK_BANNER: "{{ MFE_DISPLAY_FEEDBACK_BANNER }}"
  ENABLE_PROGRESS_GRAPH_SETTINGS: "{{ MFE_ENABLE_PROGRESS_GRAPH_SETTINGS }}"
  ENABLE_TEAM_TYPE_SETTING: "{{ MFE_ENABLE_TEAM_TYPE_SETTING }}"
  ENABLE_NEW_EDITOR_PAGES: "{{ MFE_ENABLE_NEW_EDITOR_PAGES }}"
  BBB_LEARN_MORE_URL: "{{ MFE_BBB_LEARN_MORE_URL }}"
  AUTHN_MINIMAL_HEADER: "{{ MFE_AUTHN_MINIMAL_HEADER }}"
  LOGIN_ISSUE_SUPPORT_LINK: "{{ MFE_LOGIN_ISSUE_SUPPORT_LINK }}"
  TOS_AND_HONOR_CODE: "{{ MFE_TOS_AND_HONOR_CODE }}"
  TOS_LINK: "{{ MFE_TOS_LINK }}"
  PRIVACY_POLICY: "{{ MFE_PRIVACY_POLICY }}"
  USER_SURVEY_COOKIE_NAME: "{{ MFE_USER_SURVEY_COOKIE_NAME }}"
  COOKIE_DOMAIN: "{{ MFE_COOKIE_DOMAIN  }}"
  WELCOME_PAGE_SUPPORT_LINK: "{{ MFE_WELCOME_PAGE_SUPPORT_LINK }}"
  INFO_EMAIL: "{{ MFE_INFO_EMAIL }}"
  DISABLE_ENTERPRISE_LOGIN: "{{ MFE_DISABLE_ENTERPRISE_LOGIN }}"
  REGISTER_CONVERSION_COOKIE_NAME: "{{ MFE_REGISTER_CONVERSION_COOKIE_NAME }}"
  ENABLE_COPPA_COMPLIANCE: "{{ MFE_ENABLE_COPPA_COMPLIANCE }}"
  MARKETING_EMAILS_OPT_IN: "{{ MFE_MARKETING_EMAILS_OPT_IN }}"
  ZENDESK_KEY: "{{ MFE_ZENDESK_KEY }}"
  ZENDESK_LOGO_URL: "{{ MFE_ZENDESK_LOGO_URL }}"
  APP_ID: "{{ MFE_APP_ID }}"
  MFE_CONFIG_API_URL: "{{ MFE_MFE_CONFIG_API_URL }}"
  SHOW_CONFIGURABLE_EDX_FIELDS: "{{ MFE_SHOW_CONFIGURABLE_EDX_FIELDS }}"
  SUPPORT_URL_CALCULATOR_MATH: "{{ MFE_SUPPORT_URL_CALCULATOR_MATH }}"
  SUPPORT_URL_ID_VERIFICATION: "{{ MFE_SUPPORT_URL_ID_VERIFICATION }}"
  SUPPORT_URL_VERIFIED_CERTIFICATE: "{{ MFE_SUPPORT_URL_VERIFIED_CERTIFICATE }}"

MFE_STANDALONE_NGINX: true

# NOTE: This should be overridden by inheriting MFE-specific role.
MFE_ENVIRONMENT_EXTRA: {}
MFE_ENVIRONMENT: '{{ MFE_ENVIRONMENT_DEFAULT | combine(MFE_ENVIRONMENT_EXTRA) }}'

MFE_NPM_OVERRIDES: []
