uname_r: ""

docker_common_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - cron
  - "linux-modules-extra-{{ uname_r }}"
  - linux-image-extra-virtual

docker_apt_cache_time: 86400
docker_keep_upstart: True

docker_gpg_key_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
