---
#
# edX Configuration
#
# github:     https://github.com/openedx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/openedx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role server_utils
#
# Overview:
#
# Install useful interactive utilities for triange and debugging purposes.
# Typically these would not need to be available on servers as shell access
# is uneccessary.
#
# Example play:
#
#

- name: Install ubuntu system packages
  apt:
    name: "{{ server_utils_debian_pkgs }}"
    install_recommends: yes
    state: present
    update_cache: yes
  when: ansible_distribution in common_debian_variants
