- name: test nginx config
  command: "/usr/sbin/nginx -t"
  listen: "restart nginx"

- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
  listen: "restart nginx"

- name: test nginx config
  command: "/usr/sbin/nginx -t"
  listen: "reload nginx"

- name: reload nginx
  service:
    name: nginx
    state: reloaded
  listen: "reload nginx"
