---

RETIREMENT_SERVICE_COOL_OFF_DAYS: 30
RETIREMENT_LMS_BASE_URL: "{{ EDXAPP_LMS_ROOT_URL }}"
RETIREMENT_ECOMMERCE_BASE_BASE_URL: "https://{{ ECOMMERCE_BASE }}"
RETIREMENT_CREDENTIALS_BASE_URL: "https://{{ CREDENTIALS_DOMAIN }}"
# Enable the configuration of a cron job to run this periodically
RETIREMENT_SERVICE_ENABLE_CRON_JOB: true
#Set once per day by default
RETIREMENT_SERVICE_CRON_JOB_HOURS: 0
RETIREMENT_SERVICE_CRON_JOB_MINUTES: 0

COMMON_ENABLE_ACCOUNT_DELETION: False
RETIREMENT_SERVICE_VERSION: "open-release/palm.2"

EDXAPP_RETIREMENT_SERVICE_WORKER_USERNAME: "retirement_service_worker"
EDXAPP_RETIREMENT_STATES:
  - "PENDING"
  - "LOCKING_ACCOUNT"
  - "RETIRING_FORUMS"
  - "FORUMS_COMPLETE"
  - "RETIRING_ENROLLMENTS"
  - "ENROLLMENTS_COMPLETE"
  - "RETIRING_NOTES"
  - "NOTES_COMPLETE"
  - "RETIRING_LMS_MISC"
  - "LMS_MISC_COMPLETE"
  - "RETIRING_LMS"
  - "LMS_COMPLETE"
  - "ADDING_TO_PARTNER_QUEUE"
  - "PARTNER_QUEUE_COMPLETE"
  - "ERRORED"
  - "ABORTED"
  - "COMPLETE"

RETIREMENT_SERVICE_PIPELINE_CONFIGURATION:
  - NAME: "RETIRING_FORUMS"
    NAME_COMPLETE: "FORUMS_COMPLETE"
    SERVICE: "LMS"
    FUNCTION: "retirement_retire_forum"
  - NAME: "RETIRING_ENROLLMENTS"
    NAME_COMPLETE: "ENROLLMENTS_COMPLETE"
    SERVICE: "LMS"
    FUNCTION: "retirement_unenroll"
  - NAME: "RETIRING_LMS_MISC"
    NAME_COMPLETE: "LMS_MISC_COMPLETE"
    SERVICE: "LMS"
    FUNCTION: "retirement_lms_retire_misc"
  - NAME: "RETIRING_LMS"
    NAME_COMPLETE: "LMS_COMPLETE"
    SERVICE: "LMS"
    FUNCTION: "retirement_lms_retire"

