# Bootstrap packages must be installed with raw commands, because ubuntu
# xenial+ cloud images don't have python2.7 installed, and ansible doesn't yet
# support python3.

#- name: Wait until cloud-init has finished running
#  command: test -e /usr/bin/cloud-init && cloud-init status --wait
#  ignore_errors: yes

- name: Install packages
  apt:
    pkg:
      - python3-pip
      - python3.8-minimal
    update_cache: yes

- name: Install python package
  pip:
    name: distro==1.5.0
  become: True

- name: add deadsnakes repo
  apt_repository:
      repo: ppa:deadsnakes/ppa
#- name: Update apt-get
#  command: apt-get update -qq
#  register: python_update_result
#  until: python_update_result.rc == 0
#  retries: 10
#  delay: 10
#
#- name: Install packages
#  command: "apt-get install -qq {{ item }}"
#  with_items: "{{ python_packages }}"
#  retries: 10
#  delay: 10
