---

- name: Install AWS CLI
  apt:
    name: awscli
    state: present
  tags:
    - install
    - install:base

- name: Add OS default user in tableau group
  shell: "usermod -a -G {{ tableau_user_group }} {{ os_default_user }}"
  become: yes
  become_method: sudo
  tags:
    - install
    - install:base

- name: Enable tableau user shell
  shell: "usermod -s /bin/bash {{ tableau_user }}"
  become: yes
  become_method: sudo
  tags:
    - install
    - install:base

- name: Create directory for Postgre driver if it does not exist
  file:
    path: /opt/tableau/tableau_driver/jdbc
    state: directory
    mode: '0777'
  tags:
    - install
    - install:base

- name: Download Postgre driver jar file
  get_url:
    url: "{{postgre_driver_endpoint}}/postgresql-{{postgre_driver_version}}.jar"
    dest: /opt/tableau/tableau_driver/jdbc/postgresql-{{postgre_driver_version}}.jar
  become_user: "{{ tableau_user }}"
  tags:
    - install
    - install:base

- name: Download Snowflake odbc driver
  get_url:
    url: "{{snowflake_odbc_driver_endpoint}}/{{snowflake_driver_version}}/snowflake-odbc-{{snowflake_driver_version}}.x86_64.deb"
    dest: /tmp/snowflake-odbc-{{snowflake_driver_version}}.x86_64.deb
  tags:
    - install
    - install:base

- name: Install Snowflake odbc driver
  dpkg_selections:
    name: snowflake-odbc-{{snowflake_driver_version}}.x86_64.deb
    selection: install
  tags:
    - install
    - install:base
