# Install docker-engine and docker-compose
# Add users to docker group
---
- name: add docker group
  group:
    name: "{{ docker_group }}"
  tags:
    - install
    - install:base

- name: add users to docker group
  user:
    name: "{{ item }}"
    groups: "{{ docker_group }}"
    append: yes
  with_items: "{{ docker_users }}"
  tags:
    - install
    - install:base

- name: install package dependencies
  apt:
    name: "{{ docker_tools_deps_deb_pkgs }}"
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time }}"
  tags:
    - install
    - install:system-requirements
  when: ansible_distribution_release != 'focal'

- name: install package dependencies for focal
  apt:
    name: "{{ docker_tools_deps_deb_pkgs_focal }}"
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time }}"
  tags:
    - install
    - install:system-requirements
  when: ansible_distribution_release == 'focal'

- name: add docker apt key
  apt_key:
    url: "{{ docker_apt_key_url }}"
  tags:
    - install
    - install:configuration

- name: add docker repo
  apt_repository:
    repo: "{{ item }}"
  with_items: "{{ docker_repos }}"
  tags:
    - install
    - install:configuration

- name: install docker-engine
  apt:
    name: "docker-ce"
    update_cache: yes
  tags:
    - install
    - install:system-requirements

- name: Are we in a Docker container
  shell: echo $(egrep -q 'docker' /proc/self/cgroup && echo 'yes' || echo 'no')
  ignore_errors: yes
  register: docker_container
  tags:
    - install
    - install:base

- name: start docker service
  service:
    name: docker
    enabled: yes
    state: started
  when: docker_container.stdout != 'yes'
  tags:
    - install
    - install:configuration

- name: install docker-compose
  get_url:
    dest: /usr/local/bin/docker-compose
    url: "{{ docker_compose_pkg_url }}"
    mode: 0755
  tags:
    - install
    - install:system-requirements

- name: Deploy docker-clean.sh
  copy:
    src: files/docker-clean.sh
    dest: /root/docker-clean.sh
    mode: 0750
  tags:
    - install

- name: Add docker-clean.sh to crontab
  cron:
    name: docker-clean
    job: 'nice /root/docker-clean.sh > /dev/null 2>&1'
    minute: 6
    hour: 6
    weekday: 1
  tags:
    - install
